apiVersion: v1
kind: Service
metadata:
  name: aligner-ml-app
  namespace: default
  labels:
    app: aligner-ml-app
spec:
  selector:
    app: aligner-ml-app
  ports:
  - name: http-api
    port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aligner-ml-app
spec:
  selector:
    matchLabels:
      app: aligner-ml-app
  replicas: 1
  template:
    metadata:
      labels:
        app: aligner-ml-app
      # annotations:
      #   prometheus.io/scrape: "true"
    spec:
      containers:
      - name: aligner-ml-app
        image: nginx:1.14.2
        ports:
          - containerPort: 80