apiVersion: v1
kind: Service
metadata:
  name: aligner-ml-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    # Raleigh
    - 125.16.12.82/32
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: aligner-ml-app
